apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: Profile
metadata:
  name: example-example-ran-vsphere-cluster-profile
  annotations:
    description: "vSphere Cluster Profile for Kubernetes deployment"
spec:
  forProvider:
    name: example-example-ran-vsphere-cluster-profile
    cloud: vsphere
    context: project
    type: cluster
    description: "A comprehensive cluster profile for vSphere deployment"
    version: "1.0.0"
    pack:
      - name: "ubuntu-vsphere"
        type: oci
        tag: "1.0.0"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # No customizations allowed for this OS type

      - name: "kubernetes"
        tag: "1.31.10"
        type: oci
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          

      - name: "cni-calico"
        type: oci
        tag: "3.30.2"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          
    
      - name: "csi-vsphere-csi"
        type: oci
        tag: "3.5.0"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          
          
    tags:
      - "cp:Example"
      - "cloud:vsphere"
      - "type:vsphere"
      - "version:v1.0.0"
      - "scope:cluster"
