apiVersion: cluster.palette.m.crossplane.io/v1alpha1
kind: Profile
metadata:
  name: example-example-ran-gke-cluster-profile-v2
  annotations:
    description: "GKE Cluster Profile for Kubernetes deployment - Version 2.0"
spec:
  forProvider:
    name: example-example-ran-gke-cluster-profile
    cloud: gke
    context: tenant
    type: cluster
    description: "A comprehensive cluster profile for GKE deployment - Version 2.0"
    version: "2.0.0"
    pack:
      - name: "cos-gke"
        type: oci
        tag: "1.0.0"  
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # No customizations allowed for this OS type

      - name: "kubernetes-gke"
        tag: "1.32"
        type: oci
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # No customisation is supported

      - name: "cni-vpc-native-gke"
        type: oci
        tag: "1.0.0"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # No customization is supported default values from VPC Native CNI will be applied
    
      - name: "gke-csi-gcp-driver"
        type: oci
        tag: "1.0.0"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # No customization is supported
          # Refer https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver for FIPS compliance should perform their own independent evaluation
          
    tags:
      - "cp:Example"
      - "cloud:gcp"
      - "type:gke"
      - "version:v2.0.0"
      - "scope:cluster"
  providerConfigRef:
    kind: ProviderConfig
    name: namespaced-palette-provider
