apiVersion: virtual.palette.m.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: virtual/v1alpha1/cluster
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
  namespace: upbound-system
spec:
  forProvider:
    hostClusterUid: ${var.host_cluster_uid}
    name: virtual-cluster-demo
    resources:
    - maxCpu: 6
      maxMemInMb: 6000
      minCpu: 0
      minMemInMb: 0
