/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectRoleInitParameters struct {

	// (String) Project id to be associated with the user.
	// Project id to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of project role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// References to Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v1.Reference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v1.Selector `json:"roleIdsSelector,omitempty" tf:"-"`
}

type ProjectRoleObservation struct {

	// (String) Project id to be associated with the user.
	// Project id to be associated with the user.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of project role ids to be associated with the user.
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`
}

type ProjectRoleParameters struct {

	// (String) Project id to be associated with the user.
	// Project id to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of project role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +kubebuilder:validation:Optional
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// References to Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v1.Reference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v1.Selector `json:"roleIdsSelector,omitempty" tf:"-"`
}

type ResourceRoleInitParameters struct {

	// (Set of String) List of filter ids.
	// List of filter ids.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Filter
	// +listType=set
	FilterIds []*string `json:"filterIds,omitempty" tf:"filter_ids,omitempty"`

	// References to Filter in spectrocloud to populate filterIds.
	// +kubebuilder:validation:Optional
	FilterIdsRefs []v1.Reference `json:"filterIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Filter in spectrocloud to populate filterIds.
	// +kubebuilder:validation:Optional
	FilterIdsSelector *v1.Selector `json:"filterIdsSelector,omitempty" tf:"-"`

	// (Set of String) Project id's to be associated with the user.
	// Project id's to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Project
	// +listType=set
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`

	// References to Project in spectrocloud to populate projectIds.
	// +kubebuilder:validation:Optional
	ProjectIdsRefs []v1.Reference `json:"projectIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Project in spectrocloud to populate projectIds.
	// +kubebuilder:validation:Optional
	ProjectIdsSelector *v1.Selector `json:"projectIdsSelector,omitempty" tf:"-"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of resource role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// References to Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v1.Reference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v1.Selector `json:"roleIdsSelector,omitempty" tf:"-"`
}

type ResourceRoleObservation struct {

	// (Set of String) List of filter ids.
	// List of filter ids.
	// +listType=set
	FilterIds []*string `json:"filterIds,omitempty" tf:"filter_ids,omitempty"`

	// (Set of String) Project id's to be associated with the user.
	// Project id's to be associated with the user.
	// +listType=set
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of resource role ids to be associated with the user.
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`
}

type ResourceRoleParameters struct {

	// (Set of String) List of filter ids.
	// List of filter ids.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Filter
	// +kubebuilder:validation:Optional
	// +listType=set
	FilterIds []*string `json:"filterIds,omitempty" tf:"filter_ids,omitempty"`

	// References to Filter in spectrocloud to populate filterIds.
	// +kubebuilder:validation:Optional
	FilterIdsRefs []v1.Reference `json:"filterIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Filter in spectrocloud to populate filterIds.
	// +kubebuilder:validation:Optional
	FilterIdsSelector *v1.Selector `json:"filterIdsSelector,omitempty" tf:"-"`

	// (Set of String) Project id's to be associated with the user.
	// Project id's to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	// +listType=set
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`

	// References to Project in spectrocloud to populate projectIds.
	// +kubebuilder:validation:Optional
	ProjectIdsRefs []v1.Reference `json:"projectIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Project in spectrocloud to populate projectIds.
	// +kubebuilder:validation:Optional
	ProjectIdsSelector *v1.Selector `json:"projectIdsSelector,omitempty" tf:"-"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of resource role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +kubebuilder:validation:Optional
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// References to Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v1.Reference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v1.Selector `json:"roleIdsSelector,omitempty" tf:"-"`
}

type UserInitParameters struct {

	// (String) The email of the user.
	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The first name of the user.
	// The first name of the user.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) The last name of the user.
	// The last name of the user.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// (Block Set) List of project roles to be associated with the user. (see below for nested schema)
	// List of project roles to be associated with the user.
	ProjectRole []ProjectRoleInitParameters `json:"projectRole,omitempty" tf:"project_role,omitempty"`

	// (Block Set) (see below for nested schema)
	ResourceRole []ResourceRoleInitParameters `json:"resourceRole,omitempty" tf:"resource_role,omitempty"`

	// (List of String) The team id's assigned to the user.
	// The team id's assigned to the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Team
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	// References to Team in spectrocloud to populate teamIds.
	// +kubebuilder:validation:Optional
	TeamIdsRefs []v1.Reference `json:"teamIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Team in spectrocloud to populate teamIds.
	// +kubebuilder:validation:Optional
	TeamIdsSelector *v1.Selector `json:"teamIdsSelector,omitempty" tf:"-"`

	// (Set of String) List of tenant role ids to be associated with the user.
	// List of tenant role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +listType=set
	TenantRole []*string `json:"tenantRole,omitempty" tf:"tenant_role,omitempty"`

	// References to Role in spectrocloud to populate tenantRole.
	// +kubebuilder:validation:Optional
	TenantRoleRefs []v1.Reference `json:"tenantRoleRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate tenantRole.
	// +kubebuilder:validation:Optional
	TenantRoleSelector *v1.Selector `json:"tenantRoleSelector,omitempty" tf:"-"`

	// (Block Set) List of workspace roles to be associated with the user. (see below for nested schema)
	// List of workspace roles to be associated with the user.
	WorkspaceRole []WorkspaceRoleInitParameters `json:"workspaceRole,omitempty" tf:"workspace_role,omitempty"`
}

type UserObservation struct {

	// (String) The email of the user.
	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The first name of the user.
	// The first name of the user.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The last name of the user.
	// The last name of the user.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// (Block Set) List of project roles to be associated with the user. (see below for nested schema)
	// List of project roles to be associated with the user.
	ProjectRole []ProjectRoleObservation `json:"projectRole,omitempty" tf:"project_role,omitempty"`

	// (Block Set) (see below for nested schema)
	ResourceRole []ResourceRoleObservation `json:"resourceRole,omitempty" tf:"resource_role,omitempty"`

	// (List of String) The team id's assigned to the user.
	// The team id's assigned to the user.
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	// (Set of String) List of tenant role ids to be associated with the user.
	// List of tenant role ids to be associated with the user.
	// +listType=set
	TenantRole []*string `json:"tenantRole,omitempty" tf:"tenant_role,omitempty"`

	// (Block Set) List of workspace roles to be associated with the user. (see below for nested schema)
	// List of workspace roles to be associated with the user.
	WorkspaceRole []WorkspaceRoleObservation `json:"workspaceRole,omitempty" tf:"workspace_role,omitempty"`
}

type UserParameters struct {

	// (String) The email of the user.
	// The email of the user.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (String) The first name of the user.
	// The first name of the user.
	// +kubebuilder:validation:Optional
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// (String) The last name of the user.
	// The last name of the user.
	// +kubebuilder:validation:Optional
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// (Block Set) List of project roles to be associated with the user. (see below for nested schema)
	// List of project roles to be associated with the user.
	// +kubebuilder:validation:Optional
	ProjectRole []ProjectRoleParameters `json:"projectRole,omitempty" tf:"project_role,omitempty"`

	// (Block Set) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ResourceRole []ResourceRoleParameters `json:"resourceRole,omitempty" tf:"resource_role,omitempty"`

	// (List of String) The team id's assigned to the user.
	// The team id's assigned to the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Team
	// +kubebuilder:validation:Optional
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	// References to Team in spectrocloud to populate teamIds.
	// +kubebuilder:validation:Optional
	TeamIdsRefs []v1.Reference `json:"teamIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Team in spectrocloud to populate teamIds.
	// +kubebuilder:validation:Optional
	TeamIdsSelector *v1.Selector `json:"teamIdsSelector,omitempty" tf:"-"`

	// (Set of String) List of tenant role ids to be associated with the user.
	// List of tenant role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +kubebuilder:validation:Optional
	// +listType=set
	TenantRole []*string `json:"tenantRole,omitempty" tf:"tenant_role,omitempty"`

	// References to Role in spectrocloud to populate tenantRole.
	// +kubebuilder:validation:Optional
	TenantRoleRefs []v1.Reference `json:"tenantRoleRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate tenantRole.
	// +kubebuilder:validation:Optional
	TenantRoleSelector *v1.Selector `json:"tenantRoleSelector,omitempty" tf:"-"`

	// (Block Set) List of workspace roles to be associated with the user. (see below for nested schema)
	// List of workspace roles to be associated with the user.
	// +kubebuilder:validation:Optional
	WorkspaceRole []WorkspaceRoleParameters `json:"workspaceRole,omitempty" tf:"workspace_role,omitempty"`
}

type WorkspaceRoleInitParameters struct {

	// (String) Project id to be associated with the user.
	// Project id to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Block Set, Min: 1) List of workspace roles to be associated with the user. (see below for nested schema)
	// List of workspace roles to be associated with the user.
	Workspace []WorkspaceRoleWorkspaceInitParameters `json:"workspace,omitempty" tf:"workspace,omitempty"`
}

type WorkspaceRoleObservation struct {

	// (String) Project id to be associated with the user.
	// Project id to be associated with the user.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Block Set, Min: 1) List of workspace roles to be associated with the user. (see below for nested schema)
	// List of workspace roles to be associated with the user.
	Workspace []WorkspaceRoleWorkspaceObservation `json:"workspace,omitempty" tf:"workspace,omitempty"`
}

type WorkspaceRoleParameters struct {

	// (String) Project id to be associated with the user.
	// Project id to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in spectrocloud to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Block Set, Min: 1) List of workspace roles to be associated with the user. (see below for nested schema)
	// List of workspace roles to be associated with the user.
	// +kubebuilder:validation:Optional
	Workspace []WorkspaceRoleWorkspaceParameters `json:"workspace" tf:"workspace,omitempty"`
}

type WorkspaceRoleWorkspaceInitParameters struct {

	// (String) The ID of this resource.
	// Workspace id to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Workspace
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Workspace in spectrocloud to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Workspace in spectrocloud to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.Selector `json:"idSelector,omitempty" tf:"-"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of workspace role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// References to Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v1.Reference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v1.Selector `json:"roleIdsSelector,omitempty" tf:"-"`
}

type WorkspaceRoleWorkspaceObservation struct {

	// (String) The ID of this resource.
	// Workspace id to be associated with the user.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of workspace role ids to be associated with the user.
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`
}

type WorkspaceRoleWorkspaceParameters struct {

	// (String) The ID of this resource.
	// Workspace id to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Workspace
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Reference to a Workspace in spectrocloud to populate id.
	// +kubebuilder:validation:Optional
	IDRef *v1.Reference `json:"idRef,omitempty" tf:"-"`

	// Selector for a Workspace in spectrocloud to populate id.
	// +kubebuilder:validation:Optional
	IDSelector *v1.Selector `json:"idSelector,omitempty" tf:"-"`

	// (Set of String) List of project role ids to be associated with the user.
	// List of workspace role ids to be associated with the user.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-palette/apis/spectrocloud/v1alpha1.Role
	// +kubebuilder:validation:Optional
	// +listType=set
	RoleIds []*string `json:"roleIds,omitempty" tf:"role_ids,omitempty"`

	// References to Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsRefs []v1.Reference `json:"roleIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Role in spectrocloud to populate roleIds.
	// +kubebuilder:validation:Optional
	RoleIdsSelector *v1.Selector `json:"roleIdsSelector,omitempty" tf:"-"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API. Create and manage projects in Palette.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,palette}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.firstName) || (has(self.initProvider) && has(self.initProvider.firstName))",message="spec.forProvider.firstName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.lastName) || (has(self.initProvider) && has(self.initProvider.lastName))",message="spec.forProvider.lastName is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
