apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: ApacheCloudstack
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/apachecloudstack
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    cloudAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: spectrocloud_cloudaccount_apache_cloudstack
    cloudConfig:
    - sshKeyName: my-ssh-key
      zone:
      - name: Zone1
        network:
        - id: network-id
          name: DefaultNetwork
    clusterProfile:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_cluster_profile
    machinePool:
    - additionalLabels:
        role: control-plane
      controlPlane: true
      controlPlaneAsWorker: true
      count: 1
      name: cp-pool
      network:
      - networkName: DefaultNetwork
      offering: Medium Instance
    - additionalLabels:
        role: worker
      count: 2
      name: worker-pool
      network:
      - networkName: DefaultNetwork
      offering: Large Instance
    name: apache-cloudstack-cluster-1
    tags:
    - dev
    - cloudstack
    - department:engineering
