apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: Openstack
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/openstack
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    backupPolicy:
    - backupLocationIdSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_backup_storage_location
      expiryInHour: 7200
      includeClusterResources: true
      includeDisks: true
      prefix: prod-backup
      schedule: 0 0 * * SUN
    cloudAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: spectrocloud_cloudaccount_openstack
    cloudConfig:
    - dnsServers:
      - 10.10.128.8
      - 8.8.8.8
      domain: Default
      project: dev
      region: RegionOne
      sshKey: Spectro2021
      subnetCidr: 192.168.151.0/24
    clusterProfile:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_cluster_profile
    machinePool:
    - azs:
      - zone1
      controlPlane: true
      controlPlaneAsWorker: true
      count: 1
      instanceType: spectro-xlarge
      name: cp-pool
    - azs:
      - zone1
      count: 2
      instanceType: spectro-large
      name: worker-basic
    name: openstack-piyush-tf-1
    scanPolicy:
    - configurationScanSchedule: 0 0 * * SUN
      conformanceScanSchedule: 0 0 1 * *
      penetrationScanSchedule: 0 0 * * SUN
    tags:
    - dev
