apiVersion: registration.palette.m.crossplane.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: registration/v1alpha1/token
  labels:
    testing.upbound.io/example-name: tf_token
  name: tf-token
  namespace: upbound-system
spec:
  forProvider:
    description: test token description updated
    expiryDate: "2025-03-25"
    name: tf_siva
    projectUid: 6514216503b
    status: active
