apiVersion: spectrocloud.palette.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: spectrocloud/v1alpha1/user
  labels:
    testing.upbound.io/example-name: user-test
  name: user-test
spec:
  forProvider:
    email: test-tf@spectrocloud.com
    firstName: tf
    lastName: test
    projectRole:
    - projectId: ${data.spectrocloud_project.default.id}
      roleIds: '${[for r in data.spectrocloud_role.app_roles : r.id]}'
    - projectId: ${data.spectrocloud_project.ranjith.id}
      roleIds: '${[for r in data.spectrocloud_role.app_roles : r.id]}'
    resourceRole:
    - filterIds:
      - ${data.spectrocloud_filter.filter.id}
      projectIds:
      - ${data.spectrocloud_project.default.id}
      - ${data.spectrocloud_project.ranjith.id}
      roleIds: '${[for r in data.spectrocloud_role.resource_roles : r.id]}'
    - filterIds:
      - ${data.spectrocloud_filter.filter.id}
      projectIds:
      - ${data.spectrocloud_project.ranjith.id}
      roleIds: '${[for re in data.spectrocloud_role.resource_roles_editor : re.id]}'
    teamIds:
    - ${data.spectrocloud_team.team2.id}
    tenantRole: '${[for t in data.spectrocloud_role.tenant_roles : t.id]}'
    workspaceRole:
    - projectId: ${data.spectrocloud_project.default.id}
      workspace:
      - id: ${data.spectrocloud_workspace.workspace.id}
        roleIds: '${[for w in data.spectrocloud_role.workspace_roles : w.id]}'
      - id: ${data.spectrocloud_workspace.workspace2.id}
        roleIds:
        - 66fbea622947f81fc26983e6
