apiVersion: spectrocloud.palette.crossplane.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: spectrocloud/v1alpha1/workspace
  labels:
    testing.upbound.io/example-name: workspace
  name: workspace
spec:
  forProvider:
    backupPolicy:
    - backupLocationIdSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_backup_storage_location
      clusterUids:
      - ${data.spectrocloud_cluster.cluster1.id}
      expiryInHour: 7200
      includeAllClusters: true
      includeClusterResources: true
      includeDisks: false
      prefix: prod-backup
      schedule: 0 0 * * SUN
    clusterRbacBinding:
    - role:
        kind: ClusterRole
        name: testrole3
      subjects:
      - name: testRoleUser4
        type: User
      - name: testRoleGroup4
        type: Group
      - name: testrolesubject3
        namespace: testrolenamespace
        type: ServiceAccount
      type: ClusterRoleBinding
    - namespace: test5ns
      role:
        kind: Role
        name: testrolefromns3
      subjects:
      - name: testUserRoleFromNS3
        type: User
      - name: testGroupFromNS3
        type: Group
      - name: testrolesubject3
        namespace: testrolenamespace
        type: ServiceAccount
      type: RoleBinding
    clusters:
    - uid: ${data.spectrocloud_cluster.cluster1.id}
    name: wsp-tf
    namespaces:
    - imagesBlacklist:
      - "1"
      - "2"
      - "3"
      name: test5ns
      resourceAllocation:
        cpu_cores: "2"
        memory_MiB: "2048"
