apiVersion: palette.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: cluster-provider-palette
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: palette-creds
      namespace: crossplane-system
      key: credentials
