apiVersion: cluster.palette.m.crossplane.io/v1alpha1
kind: Profile
metadata:
  name: example-example-ran-aks-cluster-profile-v2
  annotations:
    description: "AKS Cluster Profile for Kubernetes deployment"
spec:
  forProvider:
    name: example-example-ran-aks-cluster-profile
    cloud: aks
    context: project
    type: cluster
    description: "A comprehensive cluster profile for AKS deployment"
    version: "2.0.0"
    pack:
      - name: "ubuntu-aks"
        type: oci
        tag: "22.04"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # No customizations allowed for this OS type

      - name: "kubernetes-aks"
        tag: "1.32"
        type: oci
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          # AKS Kubernetes pack values

      - name: "cni-azure"
        type: oci
        tag: "1.4.0"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
          pack:
            # The Network policy for ingress and egress traffic between pods in a cluster. Supported values are azure and calico. Defaults to calico 
            networkPolicy: "calico"
    
      - name: "csi-azure"
        type: oci
        tag: "1.33.2"
        uid: "122324234"
        registryUid: "23323422242424224"
        values: |
  
          
    tags:
      - "cp:Example"
      - "cloud:aks"
      - "type:aks"
      - "version:v2.0.0"
      - "scope:cluster"
  providerConfigRef:
    kind: ProviderConfig
    name: namespaced-palette-provider
