apiVersion: backup.palette.m.crossplane.io/v1alpha1
kind: StorageLocation
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/storagelocation
  labels:
    testing.upbound.io/example-name: bsl1
  name: bsl1
  namespace: upbound-system
spec:
  forProvider:
    bucketName: dev-backup
    context: tenant
    isDefault: false
    name: dev-backup-s3
    region: us-east-2
    s3:
    - accessKey: ${var.aws_access_key}
      credentialType: ${var.credential_type}
      s3ForcePathStyle: false
      secretKeySecretRef:
        key: example-key
        name: example-secret
