apiVersion: backup.palette.crossplane.io/v1alpha1
kind: StorageLocation
metadata:
  name: gcp-backup-location
spec:
  forProvider:
    name: gcp-backup-location
    bucketName: shru-gcp-bck
    context: project
    isDefault: false
    storageProvider: gcp
     gcpStorageConfig:
      - projectId: gcpproject
        gcpJsonCredentials: |
          {
          "type": "",
          "project_id": "",
          "private_key_id": "",
          "private_key": "",
          "client_email": "",
          "client_id": "",
          "auth_uri": "",
          "token_uri": "",
          "auth_provider_x509_cert_url": "",
          "client_x509_cert_url": ""
          }
