apiVersion: cluster.jet-palette.upbound.io/v1alpha1
kind: Aws
metadata:
  name: aws-crossplane-cluster
  namespace: crossplane-system
spec:
  forProvider:
    cloudConfig:
      - sshKeyName: "exampleKey"
        region: "us-east-1"
    machinePool:
      - azs:
          - us-east-1a
        count: 3
        instanceType: t3.xlarge
        name: machinePool1
      - azs:
          - us-east-1a
        count: 1
        instanceType: t3.xlarge
        name: masterPool1
        controlPlane: true
    clusterProfile:
      - id: 633abcdfcacb8794e0c54cd7
    cloudAccountId: 63dcba95d59b2a1ea30d7859
  providerConfigRef:
    name: default