apiVersion: cloudaccount.palette.crossplane.io/v1alpha1
kind: GCP
metadata:
  name: ran-gcp-acc
spec:
  forProvider:
    name: ran-gcp-acc
    context: project  # Can be either 'project' or 'tenant'
    gcpJsonCredentials: |
      {
      "type": "",
      "project_id": "",
      "private_key_id": "",
      "private_key": "",
      "client_email": "",
      "client_id": "",
      "auth_uri": "",
      "token_uri": "",
      "auth_provider_x509_cert_url": "",
      "client_x509_cert_url": ""
      }
