apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xcustomers-aggregate
  labels:
    # This label ensures the role is aggregated into Crossplane’s main ClusterRole
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xcustomers-aggregate-binding
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xcustomers-aggregate
