apiVersion: password.palette.m.crossplane.io/v1alpha1
kind: Policy
metadata:
  name: namespaced-password-policy
  namespace: default
  annotations:
    description: "Namespaced password policy for enhanced security"
    crossplane.io/external-name: "namespaced-policy"
  labels:
    app: password-policy
    environment: production
    scope: namespaced
spec:
  forProvider:
    # Password complexity requirements
    minPasswordLength: 9
    minUppercaseLetters: 2
    minLowercaseLetters: 2
    minDigits: 2
    minSpecialCharacters: 2
    
    # Password expiry settings
    passwordExpiryDays: 333
    
    # # Reminder settings
    firstReminderDays: 7
    
    # Custom regex pattern (optional - uncomment if you want to use regex instead of individual requirements)
    # passwordRegex: "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{10,}$"
  
  # Provider configuration reference for namespaced resources
  providerConfigRef:
    kind: ClusterProviderConfig
    name: namespaced-palette-provider
  
  # Write connection details to a secret in the same namespace
  # writeConnectionSecretToRef:
  #   name: password-policy-connection-secret
