apiVersion: cluster.palette.m.crossplane.io/v1alpha1
kind: Eks
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/eks
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
  namespace: upbound-system
spec:
  forProvider:
    backupPolicy:
    - backupLocationIdSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_backup_storage_location
      expiryInHour: 7200
      includeClusterResources: true
      includeDisks: true
      prefix: prod-backup
      schedule: 0 0 * * SUN
    cloudAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: spectrocloud_cloudaccount_aws
    cloudConfig:
    - region: us-west-2
      sshKeyName: default
    clusterProfile:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_cluster_profile
    machinePool:
    - azSubnets:
        us-west-2a: subnet-0d4978ddbff16c
      count: 1
      diskSizeGb: 60
      encryption_config_arn: arn:aws:kms:us-west-2:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab
      instanceType: t3.large
      name: worker-basic
    name: ${var.cluster_name}
    scanPolicy:
    - configurationScanSchedule: 0 0 * * SUN
      conformanceScanSchedule: 0 0 1 * *
      penetrationScanSchedule: 0 0 * * SUN
    tags:
    - dev
    - department:devops
    - owner:bob
