apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: Azure
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/azure
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    cloudAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: spectrocloud_cloudaccount_azure
    cloudConfig:
    - region: ${var.azure_region}
      resourceGroup: ${var.azure_resource_group}
      sshKey: ${var.cluster_ssh_public_key}
      subscriptionId: ${var.azure_subscription_id}
    clusterProfile:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_cluster_profile
    machinePool:
    - azs:
      - ""
      controlPlane: true
      controlPlaneAsWorker: true
      count: 1
      disk:
      - sizeGb: 65
        type: Standard_LRS
      instanceType: Standard_D2_v3
      name: cp-pool
    - azs:
      - ""
      count: 1
      instanceType: Standard_D2_v3
      name: worker-basic
    name: ${var.cluster_name}
    tags:
    - dev
    - department:devops
    - owner:bob
