apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: GCP
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/gcp
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    cloudAccountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: spectrocloud_cloudaccount_gcp
    cloudConfig:
    - network: ${var.gcp_network}
      project: ${var.gcp_project}
      region: ${var.gcp_region}
    clusterProfile:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_cluster_profile
    machinePool:
    - azs:
      - us-west3-a
      controlPlane: true
      controlPlaneAsWorker: true
      count: 1
      diskSizeGb: 62
      instanceType: e2-standard-2
      name: cp-pool
    - azs:
      - us-west3-a
      count: 1
      instanceType: e2-standard-2
      name: worker-basic
    name: ${var.cluster_name}
    tags:
    - dev
    - department:devops
    - owner:bob
