apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: Maas
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/maas
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    backupPolicy:
    - backupLocationId: ${data.spectrocloud_backup_storage_location.bsl.id}
      expiryInHour: 7200
      includeClusterResources: true
      includeDisks: true
      prefix: prod-backup
      schedule: 0 0 * * SUN
    cloudAccountId: ${data.spectrocloud_cloudaccount_maas.account.id}
    cloudConfig:
    - region: centralus
      resource_group: dev
      ssh_key: ssh key value
      subscription_id: subscription-id
    clusterProfile:
    - id: ${data.spectrocloud_cluster_profile.profile.id}
    machinePool:
    - count: 1
      disk_size_gb: 60
      instanceType: Standard_DS4
      is_system_node_pool: true
      name: worker-basic
      storage_account_type: Standard_LRS
    scanPolicy:
    - configurationScanSchedule: 0 0 * * SUN
      conformanceScanSchedule: 0 0 1 * *
      penetrationScanSchedule: 0 0 * * SUN
    tags:
    - dev
    - department:devops
    - owner:bob
