apiVersion: spectrocloud.palette.m.crossplane.io/v1alpha1
kind: Alert
metadata:
  annotations:
    meta.upbound.io/example-id: spectrocloud/v1alpha1/alert
  labels:
    testing.upbound.io/example-name: alert_email
  name: alert-email
  namespace: crossplane-system
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: provider-palette
  forProvider:
    alertAllUsers: false
    component: ClusterHealth
    identifiers: []
    isActive: true
    project: Default
    type: email

