apiVersion: cluster.palette.crossplane.io/v1alpha1
kind: Azure
metadata:
  annotations:
    meta.upbound.io/example-id: cluster/v1alpha1/azure
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    cloudAccountId: ${data.spectrocloud_cloudaccount_azure.account.id}
    cloudConfig:
    - region: ${var.azure_region}
      resourceGroup: ${var.azure_resource_group}
      sshKey: ${var.cluster_ssh_public_key}
      subscriptionId: ${var.azure_subscription_id}
    clusterProfile:
    - id: ${data.spectrocloud_cluster_profile.profile.id}
    machinePool:
    - azs:
      - ""
      controlPlane: true
      controlPlaneAsWorker: true
      count: 1
      disk:
      - sizeGb: 65
        type: Standard_LRS
      instanceType: Standard_D2_v3
      name: master-pool
    - azs:
      - ""
      count: 1
      instanceType: Standard_D2_v3
      name: worker-basic
    tags:
    - dev
    - department:devops
    - owner:bob
