# Combined Provider Installation and Configuration
# This file installs the Palette provider and configures it with credentials

---
# Install the Palette Provider
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-palette
spec:
  package: crossplane-contrib/provider-palette:latest

---
# Configure the Provider with credentials
apiVersion: palette.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: palette-creds
      namespace: crossplane-system
      key: credentials 