/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *DeveloperSetting) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RegistrationToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSO) Hub() {}
