apiVersion: spectrocloud.palette.m.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: spectrocloud/v1alpha1/application
  labels:
    testing.upbound.io/example-name: application
  name: application
  namespace: upbound-system
spec:
  forProvider:
    applicationProfileUidSelector:
      matchLabels:
        testing.upbound.io/example-name: spectrocloud_application_profile
    config:
    - clusterGroupUidSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      clusterName: sandbox-scorpius
      limits:
      - cpu: 2
        memory: 4096
        storage: 10
    name: app-beru-whitesun-lars
