apiVersion: spectrocloud.palette.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: spectrocloud/v1alpha1/team
  labels:
    testing.upbound.io/example-name: t1
  name: t1
  namespace: upbound-system
spec:
  forProvider:
    name: team1
    projectRoleMapping:
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_project
      rolesRefs:
      - name: spectrocloud_role
      - name: spectrocloud_role
    - idSelector:
        matchLabels:
          testing.upbound.io/example-name: spectrocloud_project
      rolesRefs:
      - name: spectrocloud_role
    usersRefs:
    - name: spectrocloud_user
