apiVersion: cloudaccount.palette.m.crossplane.io/v1alpha1
kind: Custom
metadata:
  annotations:
    meta.upbound.io/example-id: cloudaccount/v1alpha1/custom
  labels:
    testing.upbound.io/example-name: cloud_account
  name: cloud-account
  namespace: upbound-system
spec:
  forProvider:
    cloud: nutanix
    context: tenant
    credentialsSecretRef:
      key: example-key
      name: example-secret
    name: test-custom-cloud-account
    privateCloudGatewayId: ${data.spectrocloud_private_cloud_gateway.nutanix_pcg.id}
