apiVersion: addon.palette.crossplane.io/v1alpha1
kind: Deployment
metadata:
  annotations:
    meta.upbound.io/example-id: addon/v1alpha1/deployment
    description: "Addon Deployment for testing"
  labels:
    testing.upbound.io/example-name: addon-deployment
  name: cp-addon-deployment
spec:
  forProvider:
    context: project
    clusterUid: "<YOUR_CLUSTER_UID>"
    applySetting: DownloadAndInstall
    clusterProfile:
      - id: "<YOUR_ADDON_PROFILE_ID>"
