apiVersion: privatecloudgateway.palette.crossplane.io/v1alpha1
kind: DNSMap
metadata:
  annotations:
    meta.upbound.io/example-id: privatecloudgateway/v1alpha1/dnsmap
    description: "DNS Map for Private Cloud Gateway"
  labels:
    testing.upbound.io/example-name: dns_map_test
  name: dns-map-test
spec:
  forProvider:
    dataCenter: DataCenterTest
    network: TEST-VM-NETWORK
    privateCloudGatewayId: "<YOUR_PRIVATE_CLOUD_GATEWAY_ID>"
    searchDomainName: test1.spectro.com
