apiVersion: password.palette.crossplane.io/v1alpha1
kind: Policy
metadata:
  name: ran-cp-password-policy
spec:
  forProvider:
    passwordExpiryDays: 999
    firstReminderDays: 7
    passwordRegex: "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{12,}$"
  deletionPolicy: Delete
