apiVersion: password.palette.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: password/v1alpha1/policy
    description: "Password policy for Palette project"
    crossplane.io/external-name: "default"
  labels:
    testing.upbound.io/example-name: password-policy
  name: password-policy
spec:
  forProvider:
    firstReminderDays: 5
    minDigits: 1
    minLowercaseLetters: 1
    minPasswordLength: 12
    minSpecialCharacters: 1
    minUppercaseLetters: 1
    passwordExpiryDays: 999
