apiVersion: cloudaccount.palette.crossplane.io/v1alpha1
kind: Maas
metadata:
  annotations:
    meta.upbound.io/example-id: cloudaccount/v1alpha1/maas
  labels:
    testing.upbound.io/example-name: maas-1
  name: maas-1
spec:
  forProvider:
    maasApiEndpoint: ${var.maas_api_endpoint}
    maasApiKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
